import type { Result } from 'execa'
import { $ } from 'execa'
import { nanoid } from 'nanoid'
import fs from 'node:fs/promises'
import os from 'node:os'
import path from 'node:path'
import { describe, expect, it } from 'vitest'

function getTempPath(): { name: string; output: string; path: string } {
	const thePath = path.join(os.tmpdir(), `${nanoid()}.md`)
	return {
		name: path.basename(thePath),
		output: path.dirname(thePath),
		path: thePath,
	}
}

describe('mdat cli tool', () => {
	it('should demand a command', async () => {
		let result: Result | undefined
		try {
			result = await $`./bin/cli.js`
		} catch (error) {
			if (error) {
				result = error as Result
			}
		}

		expect(result).toBeDefined()
		const { exitCode, failed } = result!
		expect(exitCode).toEqual(1)
		expect(failed).toEqual(true)
	})

	it('should run expand command', async () => {
		const { name, output, path } = getTempPath()

		try {
			await $`./bin/cli.js expand ./test/assets/test-document.md --rules ./test/assets/test-rules.ts --output ${output} --name ${name}`
		} catch {
			// // Returns 1 because of validation errors, ignore
		}

		const result = await fs.readFile(path, 'utf8')
		expect(result).toMatchSnapshot()
	})

	it('should run expand command by default', async () => {
		const { name, output, path } = getTempPath()

		try {
			await $`./bin/cli.js ./test/assets/test-document.md --rules ./test/assets/test-rules.ts --output ${output} --name ${name}`
		} catch {
			// // Returns 1 because of validation errors, ignore
		}

		const result = await fs.readFile(path, 'utf8')
		expect(result).toMatchSnapshot()
	})

	it('should handle json rules', async () => {
		const { name, output, path } = getTempPath()

		try {
			await $`./bin/cli.js ./test/assets/test-document.md --rules ./test/assets/test-rules-json.json --output ${output} --name ${name}`
		} catch {
			// // Returns 1 because of validation errors, ignore
		}

		const result = await fs.readFile(path, 'utf8')
		expect(result).toMatchSnapshot()
	})

	it('help', async () => {
		// Ensure the print width is correct
		const { stdout } = await $`./bin/cli.js --help`
		const longestLineLength = stdout
			.split('\n')
			// eslint-disable-next-line unicorn/no-array-reduce
			.reduce((a, b) => (a.length > b.length ? a : b)).length
		expect(longestLineLength).toBeGreaterThanOrEqual(120)
	})

	it('should accept --meta as boolean true', async () => {
		const { name, output, path } = getTempPath()

		try {
			await $`./bin/cli.js expand ./test/assets/test-document.md --rules ./test/assets/test-rules.ts --output ${output} --name ${name} --meta`
		} catch {
			// Returns 1 because of validation errors, ignore
		}

		const result = await fs.readFile(path, 'utf8')
		// Should contain the default meta comment
		expect(result).toContain('Warning: Content inside HTML comment blocks was generated by mdat')
		expect(result).toMatchSnapshot()
	})

	it('should accept --meta as boolean false', async () => {
		const { name, output, path } = getTempPath()

		try {
			await $`./bin/cli.js expand ./test/assets/test-document.md --rules ./test/assets/test-rules.ts --output ${output} --name ${name} --meta false`
		} catch {
			// Returns 1 because of validation errors, ignore
		}

		const result = await fs.readFile(path, 'utf8')
		// Should NOT contain the meta comment
		expect(result).not.toContain(
			'Warning: Content inside HTML comment blocks was generated by mdat',
		)
		expect(result).toMatchSnapshot()
	})

	it('should accept --meta as a custom string', async () => {
		const { name, output, path } = getTempPath()
		const customMessage = 'Custom warning: Do not edit'

		try {
			await $`./bin/cli.js expand ./test/assets/test-document.md --rules ./test/assets/test-rules.ts --output ${output} --name ${name} --meta ${customMessage}`
		} catch {
			// Returns 1 because of validation errors, ignore
		}

		const result = await fs.readFile(path, 'utf8')
		// Should contain the custom meta comment
		expect(result).toContain(`<!--+ ${customMessage} +-->`)
		expect(result).toMatchSnapshot()
	})

	it('should accept -m as boolean shorthand', async () => {
		const { name, output, path } = getTempPath()

		try {
			await $`./bin/cli.js expand ./test/assets/test-document.md --rules ./test/assets/test-rules.ts --output ${output} --name ${name} -m`
		} catch {
			// Returns 1 because of validation errors, ignore
		}

		const result = await fs.readFile(path, 'utf8')
		// Should contain the default meta comment
		expect(result).toContain('Warning: Content inside HTML comment blocks was generated by mdat')
	})

	it('should accept -m with a custom string', async () => {
		const { name, output, path } = getTempPath()
		const customMessage = 'Short form custom message'

		try {
			await $`./bin/cli.js expand ./test/assets/test-document.md --rules ./test/assets/test-rules.ts --output ${output} --name ${name} -m ${customMessage}`
		} catch {
			// Returns 1 because of validation errors, ignore
		}

		const result = await fs.readFile(path, 'utf8')
		// Should contain the custom meta comment
		expect(result).toContain(`<!--+ ${customMessage} +-->`)
	})

	it('should use config file meta comment when no CLI option is provided', async () => {
		const { name, output, path } = getTempPath()

		try {
			await $`./bin/cli.js expand ./test/assets/test-document.md --rules ./test/assets/test-rules.ts --config ./test/assets/test-config-with-meta.ts --output ${output} --name ${name}`
		} catch {
			// Returns 1 because of validation errors, ignore
		}

		const result = await fs.readFile(path, 'utf8')
		// Should contain the config file meta comment
		expect(result).toContain('<!--+ Config file meta comment +-->')
		expect(result).toMatchSnapshot()
	})

	it('should allow CLI option to override config file meta comment', async () => {
		const { name, output, path } = getTempPath()
		const cliMessage = 'CLI override message'

		try {
			await $`./bin/cli.js expand ./test/assets/test-document.md --rules ./test/assets/test-rules.ts --config ./test/assets/test-config-with-meta.ts --output ${output} --name ${name} --meta ${cliMessage}`
		} catch {
			// Returns 1 because of validation errors, ignore
		}

		const result = await fs.readFile(path, 'utf8')
		// Should contain the CLI meta comment, not the config file one
		expect(result).toContain(`<!--+ ${cliMessage} +-->`)
		expect(result).not.toContain('Config file meta comment')
		expect(result).toMatchSnapshot()
	})

	it('should allow CLI false to override config file meta comment', async () => {
		const { name, output, path } = getTempPath()

		try {
			await $`./bin/cli.js expand ./test/assets/test-document.md --rules ./test/assets/test-rules.ts --config ./test/assets/test-config-with-meta.ts --output ${output} --name ${name} --meta false`
		} catch {
			// Returns 1 because of validation errors, ignore
		}

		const result = await fs.readFile(path, 'utf8')
		// Should NOT contain any meta comment
		expect(result).not.toContain('<!--+')
		expect(result).not.toContain('Config file meta comment')
		expect(result).toMatchSnapshot()
	})
})

// Shell expansion doesn't work in test
// it('should run expand command on multiple files', async () => {
// 	const { stdout } = await $`./bin/cli.js ./test/assets/*.md --rules ./test/assets/test-rules.ts`

// 	console.log(stdout)

// 	expect('hi').toEqual('hi')
// })
