packages:
  - '.'
overrides:
  normalize-package-data: ^9.0.0
publicHoistPattern:
  - '@kitschpatrol/repo-config'
  - '@kitschpatrol/typescript-config'
  - 'case-police'
  - '*cspell*'
  - '*eslint*'
  - '*knip*'
  - '*mdat*'
  - '*prettier*'
  - '*remark*'
  - '*stylelint*'
allowBuilds:
  puppeteer: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - remark-mdat@3.1.0
