packages:
  - '.'
overrides:
  normalize-package-data: ^9.0.0
publicHoistPattern:
  - '@kitschpatrol/repo-config'
  - '@kitschpatrol/typescript-config'
  - 'case-police'
  - '*cspell*'
  - '*eslint*'
  - '*knip*'
  - '*mdat*'
  - '*prettier*'
  - '*remark*'
  - '*stylelint*'
allowBuilds:
  puppeteer: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@kitschpatrol/cspell-config@8.11.0'
  - '@kitschpatrol/eslint-config@8.11.0'
  - '@kitschpatrol/knip-config@8.11.0'
  - '@kitschpatrol/mdat-config@8.11.0'
  - '@kitschpatrol/prettier-config@8.11.0'
  - '@kitschpatrol/remark-config@8.11.0'
  - '@kitschpatrol/repo-config@8.11.0'
  - '@kitschpatrol/shared-config@8.11.0'
  - '@kitschpatrol/stylelint-config@8.11.0'
  - '@kitschpatrol/typescript-config@8.11.0'
  - '@pnpm/lockfile.fs@1100.2.12'
  - eslint-plugin-jsdoc@65.1.0
  - mdat-plugin-cli-help@3.4.0
  - mdat@3.5.0
